### ISSUE TITLE
扫描结果 -F 读取卡死

### ISSUE THREAD

**Issue by yz1639** [chainreactors/gogo#69]
![image](https://github.com/chainreactors/gogo/assets/44149984/e8681731-7d83-4132-9490-93b850a2171a)

文件有81mb, 在服务器上完全看不了,我拖到本地后 就如上图这两行, 没有其他输出 一直卡着 是没扫到东西吗?

```
# ./gogo -F .192.168.19.0.24_20-65535_default_jl.dat 
Killed
```

**Comment by M09Ic** [comment]
还是内存 OOM的问题。 可以试试这个脚本 https://github.com/chainreactors/gogo/blob/dev/tools/format.py 

`python format.py 1.dat`

**Comment by yz1639** [comment]
> 还是内存 OOM的问题。 可以试试这个脚本 https://github.com/chainreactors/gogo/blob/dev/tools/format.py
> 
> `python format.py 1.dat`

```
python formart.py gSH7x.dat -e protocol!=tcp
gSH7x.dat
Traceback (most recent call last):
  File "/Users/lt/Downloads/formart.py", line 354, in <module>
    main()
  File "/Users/lt/.pyenv/versions/3.11.3/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lt/.pyenv/versions/3.11.3/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/lt/.pyenv/versions/3.11.3/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lt/.pyenv/versions/3.11.3/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lt/Downloads/formart.py", line 340, in main
    results = results.exprs(exprs, _or)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lt/Downloads/formart.py", line 199, in exprs
    results = results.expr(expr)
              ^^^^^^^^^^^^^^^^^^
  File "/Users/lt/Downloads/formart.py", line 186, in expr
    k, v, isequal, isnot = self.split_expr(expr)
                           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lt/Downloads/formart.py", line 174, in split_expr
    for key in ResultJson.json:
               ^^^^^^^^^^^^^^^
AttributeError: type object 'ResultJson' has no attribute 'json'
```

加了条件就报错不加条件半天输出不完

**Comment by M09Ic** [comment]
因为这个脚本比较老了，昨天临时修复了下基本功能。 过滤功能暂时使用grep代替吧
